### ISSUE TITLE
Choose an inline-documentation system

### ISSUE THREAD

**Issue by clint-tseng** [nafundi/jubilant-garbanzo#15]
The answer might be "Other: inline-documentation sucks, do this instead."

But especially since JS is dynamically typed, there needs to be an easy API function signature reference of some kind.

**Comment by clint-tseng** [comment]
Somebody I follow made http://documentation.js.org/ but i have no idea if it's any good.

**Comment by matthew-white** [comment]
I like the idea of documenting function parameters and their types, functions' return values and their types, etc. JSDoc seems fairly common and would allow us to autogenerate documentation, so that seems like a good approach to me. If we go with JSDoc, we could go with documentation.js or another JSDoc-based system. @lognaturel, @ggalmazor, what do you think?

**Comment by matthew-white** [comment]
:+1: to waiting on implementing this. Once we do, I think documentation.js or another form of JSDoc would be a good place to start.

**Comment by clint-tseng** [comment]
As discussed on Slack, we are going to use a revolutionary concept called comments to do this.
